#url: https://xorote.github.io
#baseurl: #

# Site settings
title: Gigarad
email: gautham@gigarad.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Build settings
markdown: kramdown
permalink: pretty