#url: https://xorote.github.io
#baseurl: #

# Site settings
title: Gigarad
email: gautham@gigarad.com
description: "Mobile Application Development | Ideate | Design | Build | Deliver | App"

# Build settings
markdown: kramdown
permalink: pretty